name: Checkmarx AST Github Action

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: DemetryKotrozinis/tested
          base_uri: https://eu.ast.checkmarx.net/
          cx_tenant: beta_nova8
          cx_client_id: ${{secrets.CX_CLIENT_ID}}
          cx_client_secret: ${{secrets.CX_CLIENT_SECRET}}
